// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGylyZv3XC_vO8wHNRT8FE3a3hZDAabcE',
    appId: '1:267475565135:web:148627f15027c1a6ca083a',
    messagingSenderId: '267475565135',
    projectId: 'hhs-album',
    authDomain: 'hhs-album.firebaseapp.com',
    storageBucket: 'hhs-album.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClz90ll-gicioyQt9h_eVyfGX_fDo8E-s',
    appId: '1:267475565135:android:62b9d763fa1cd6a2ca083a',
    messagingSenderId: '267475565135',
    projectId: 'hhs-album',
    storageBucket: 'hhs-album.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADNeKznoeSWltdhN8WvL2tPTDeOif4LhE',
    appId: '1:267475565135:ios:10ed3384e3e1169dca083a',
    messagingSenderId: '267475565135',
    projectId: 'hhs-album',
    storageBucket: 'hhs-album.firebasestorage.app',
    iosBundleId: 'com.example.hhsAlbum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADNeKznoeSWltdhN8WvL2tPTDeOif4LhE',
    appId: '1:267475565135:ios:10ed3384e3e1169dca083a',
    messagingSenderId: '267475565135',
    projectId: 'hhs-album',
    storageBucket: 'hhs-album.firebasestorage.app',
    iosBundleId: 'com.example.hhsAlbum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGylyZv3XC_vO8wHNRT8FE3a3hZDAabcE',
    appId: '1:267475565135:web:75af0d8eac73c236ca083a',
    messagingSenderId: '267475565135',
    projectId: 'hhs-album',
    authDomain: 'hhs-album.firebaseapp.com',
    storageBucket: 'hhs-album.firebasestorage.app',
  );
}
